# Generated by Django 2.2.2 on 2021-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='publications_date',
            field=models.DateField(),
        ),
    ]
